name       : gnome-system-tools
version    : 3.0.0
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-system-tools/3.0/gnome-system-tools-3.0.0.tar.gz : ba92ad7872a655d054bfb143efb38615570698826c88a88b367b524468d0ab10
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : System configuration tools
description: |
    System configuration tools
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(liboobs-1)
    - pkgconfig(system-tools-backends-2.0)
    - gnome-doc-utils
    - intltool
rundeps    :
    - system-tools-backends
setup      : |
    %apply_patches
    autoreconf -vfi
    intltoolize -f
    %configure --disable-services \
        --disable-nautilus \
        --disable-scrollkeeper \
        --disable-schemas-install \
        --disable-users \
        LIBS="-lm -lgthread-2.0"
build      : |
    %make
install    : |
    %make_install
